### ISSUE TITLE
Parsing an array of tables errors

### ISSUE THREAD

**Issue by jamesjwarren** [alexbeletsky/toml-js#4]
Doesn't seem to support toml's [array-of-tables](https://github.com/toml-lang/toml#array-of-tables).

Parsing this structure returns an error:
```toml
[[resources]]
name = "Article"

[[resources]]
name = "Post"
```
```
Error: "[resources" is overriding existing value
toml.js:40
    at addGroup (./node_modules/toml-js/lib/amd/toml.js:40:1)
    at parseGroup (./node_modules/toml-js/lib/amd/toml.js:26:1)
    at parseLine (./node_modules/toml-js/lib/amd/toml.js:140:1)
    at ./node_modules/toml-js/lib/amd/toml.js:167:1
    at Array.forEach (<anonymous>)
    at parse (./node_modules/toml-js/lib/amd/toml.js:165:1)
    at Object.startParser [as parse] (./node_modules/toml-js/lib/amd/toml.js:218:1)
    at ./src/App.js:36:1
    at <anonymous>
```

**Comment by aloisdg** [comment]
[online demo of the problem](https://jsfiddle.net/9ae7uzsa/1/)

**Comment by alexbeletsky** [comment]
@jamesjwarren @aloisdg you are right guys, the time I implemented this `toml` did have that feature, or I missed it somehow. 

Does anyone want to submit a PR to support that?
